baseURL = "https://stkokoninetlifycms.z11.web.core.windows.net/"
languageCode = "ja-jp"
title = "Hugo-NetlifyCMS-Trial"

author = "hiroyu kinoshita"
copyright = "TestSite"

theme = "bootstrap-bp-hugo-theme"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
pygmentsCodeFences = true
canonifyurls = true
paginate = 5

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[Author]
  name = "hiroyu kinoshita"

[params]
  description = "This is a Test Site! That's it!!"
  # images = ["logo.jpg"]
  # showPostSummary = true
  # startPageColumns = true
  # showListsGrouped = true
  # alwaysExpandMenu = true
  customDateFormat = "2006/01/02"
  hideReadingTime = true
  themeColor="blue" # dark, light, blue, do not set for bootstrap default
  # js=["/js/test_site.js"]
  # css=["/css/test_site.css"]
  # csscdn=["https://fonts.googleapis.com/css?family=Concert+One|Roboto&display=swap"]

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 9
    pre = "<i class='fas fa-newspaper'></i>"

  [[menu.main]]
    identifier = "article"
    name = "Article"
    url = "/article/"
    weight = 20
    pre = "<i class='fas fa-newspaper'></i>"

[social]
  # Coding Communities
  github           = ""
  gitlab           = ""
  stackoverflow    = "" # User Number
  bitbucket        = ""
  jsfiddle         = ""
  codepen          = ""
  # Visual Art Communities
  deviantart       = ""
  flickr           = ""
  behance          = ""
  dribbble         = ""
  # Publishing Communities
  wordpress        = ""
  medium           = ""
  # Professional/Business Oriented Communities
  linkedin         = ""
  linkedin_company = ""
  foursquare       = ""
  xing             = ""
  slideshare       = ""
  # Social Networks
  facebook         = "" # https://fb.me/spech.de
  googleplus       = ""
  reddit           = ""
  quora            = ""
  youtube          = "" # https://www.youtube.com/channel/UCrRRKovAoTYGIIB9T08pbHw
  vimeo            = ""
  whatsapp         = "" # WhatsApp Number
  instagram        = "" # https://www.instagram.com/flowartsde/
  tumblr           = ""
  twitter          = ""
  skype            = ""
  snapchat         = ""
  pinterest        = ""
  telegram         = ""
  discord          = "" # invite link
  # Email
  email            = ""

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disable = false
    simple = true

  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disable = false
    simple = true

  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true