backend:
  name: github
  repo: kinoshitahiroyuki/HugoSite
  branch: master

media_folder: "site/static/images"
public_folder: "img"
publish_mode: editorial_workflow
locale: "ja"

collections:
  - label: "Blog" # 管理画面のサイドバーで使う
    name: "blog" # 管理画面のパスで使う　例：/admin/collections/blog
    folder: "site/content/blog" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - { label: "メタ情報", name: "description", widget: "text"}
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "サムネイル画像", name: "thumbnail", widget: "image" }
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "Public", name: "public", widget: "boolean", default: true}
  - label: "Article" # 管理画面のサイドバーで使う
    name: "article" # 管理画面のパスで使う
    folder: "site/content/article" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - { label: "メタ情報", name: "description", widget: "text"}
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "サムネイル画像", name: "thumbnail", widget: "image" }
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "Public", name: "public", widget: "boolean", default: true}